export class BillModel {
  id: number | undefined;
  ma: string = '';
  ngayTao: string = '';
  ngayThanhToan: string = '';
  hinhThucGiaoHang: number = 0;
  hinhThucThanhToan: number = 0;
  tenNguoiNhan: string = '';
  sdtNguoiNhan: string = '';
  tenNguoiShip: string = '';
  sdtNguoiShip: string = '';
  diaChi: string = '';
  tongTien: number = 0;
  tienShip: number = 0;
  tienGiamGia: number = 0;
  tongThanhToan: number = 0;
  tienMat: number = 0;
  chuyenKhoan: number = 0;
  trangThai: number = 0;
  ghiChu: string = '';
  loaiHoaDon: number = 0;
  trangThaiGiaoHang: number = 0;
  idKhachHang: number | undefined;
  tenKhachHang: string = '';
  idUser: number | undefined;
  userEmail: string = '';
}
